#include "p16f84a.inc"
; CONFIG
; __config 0xFFF9
__CONFIG _FOSC_HS & _WDTE_OFF & _PWRTE_OFF & _CP_OFF

CBLOCK    0X10
    HCYCLY
ENDC
    ORG     0X00
    GOTO    SETUP
    ORG     0X04
    RETFIE

SETUP
    CALL    SETPORT 
    GOTO    MAIN
    
MAIN
    CALL    HALT_CHECK
    BSF	    PORTA, 0
    MOVF    PORTB, W
    CALL    DELAY
    
    CALL    HALT_CHECK
    BCF	    PORTA, 0
    MOVF    PORTB, W
    CALL    DELAY
    GOTO    MAIN
    
SETPORT
    BSF	    STATUS, RP0
    CLRF    TRISA
    MOVLW   0XFF
    MOVWF   TRISB
    BCF	    STATUS, RP0
    RETURN
    
HALT_CHECK
    MOVF    PORTB, W
    ADDLW   0X01
    BTFSS   STATUS, Z
    RETURN
    
    BCF	    PORTA, 0
    GOTO    HALT_CHECK
    
DELAY
    MOVWF   HCYCLY
    MOVF    HCYCLY, F
    BTFSC   STATUS, Z
    RETURN
DELAY_1
    DECFSZ  HCYCLY, F
    GOTO    DELAY_1
    RETURN

    END